name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-rules-gtsam:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Bazel
        uses: philwo/setup-bazel@v1
        with:
          version: 5.0.0  # Specify the Bazel version you want

      - name: Set Commit SHA
        # Store the commit SHA that triggered the job in an environment variable
        run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Create test WORKSPACE
        run: |
          mkdir test_workspace
          cd test_workspace
          echo 'workspace(name = "test_gtsam_workspace")' > WORKSPACE
          echo "
          load(\"@bazel_tools//tools/build_defs/repo:http.bzl\", \"http_archive\")

          # Add your rules_gtsam repository as an http_archive with the current commit hash
          http_archive(
              name = \"rules_gtsam\",
              urls = [\"https://github.com/your_username/rules_gtsam/archive/${COMMIT_SHA}.zip\"],
              strip_prefix = \"rules_gtsam-${COMMIT_SHA}\",
          )

          # Load Google Test
          http_archive(
              name = \"com_google_googletest\",
              urls = [\"https://github.com/google/googletest/archive/release-1.11.0.zip\"],
              strip_prefix = \"googletest-release-1.11.0\",
          )

          # Load any other dependencies like Boost, if required by GTSAM
          load(\"@rules_boost//:boost/boost.bzl\", \"boost_deps\")
          boost_deps()
          " >> WORKSPACE

      - name: Create BUILD file for testing
        run: |
          cd test_workspace
          echo '
          load("@rules_gtsam//bzl:gtsam.bzl", "gtsam_import")

          gtsam_import(
              name = "test_gtsam_import",
              srcs = ["test.cpp"],
              deps = [
                  "@boost//:boost",
                  "@rules_gtsam//:gtsam",
                  "@com_google_googletest//:gtest",
                  "@com_google_googletest//:gtest_main",
              ],
          )

          cc_test(
              name = "test_gtsam",
              srcs = ["test.cpp"],
              deps = [
                  ":test_gtsam_import",
                  "@com_google_googletest//:gtest",
                  "@com_google_googletest//:gtest_main",
              ],
          )
          ' > BUILD

      - name: Add Test File
        run: |
          echo '
          #include <gtsam/geometry/Point3.h>
          #include <gtest/gtest.h>

          TEST(GtsamTest, Point3Coordinates) {
              gtsam::Point3 point(1.0, 2.0, 3.0);
              EXPECT_EQ(point.x(), 1.0);
              EXPECT_EQ(point.y(), 2.0);
              EXPECT_EQ(point.z(), 3.0);
          }

          int main(int argc, char **argv) {
              ::testing::InitGoogleTest(&argc, argv);
              return RUN_ALL_TESTS();
          }
          ' > test_workspace/test.cpp

      - name: Run Bazel Test
        working-directory: test_workspace
        run: |
          bazel test //:test_gtsam --test_output=errors
